### ISSUE TITLE
Files in 2.12

### ISSUE THREAD

**Issue by davidarellano** [RedHate/AIR-Plugin-Patcher#3]
Hello, it seems they moved this data outside the binary into separate files in the same path where the `SESSION` is stored as well.

Each of those files are named using the same values in `plugin_name[]`.
https://github.com/RedHate/AIR-Plugin-Patcher/blob/b616f50355bdbf1c18733d8bed4b7dcb94c3a846/mpc-plugin-patcher.c#L42-L55

The data inside seems to be 5 chunks separated by `.` and encoded in `base64`, once decoded I've found a JSON with creation and expiration dates, userId, and the data you have also in `plugin_block[]`. Each file matches its data chunk.
https://github.com/RedHate/AIR-Plugin-Patcher/blob/b616f50355bdbf1c18733d8bed4b7dcb94c3a846/mpc-plugin-patcher.c#L57-L70

I've tried to perform the actions of the current code of the patcher manually on these files: making a copy of a owned file, replacing name and block, and changing the expiration date, but nothing worked for me. I'm not sure what to do next.

Would you mind to take a look at it again so we could find what's missing and get a working script for these new files?

cc: @RedHate @dagss-offcutz

**Comment by dagss-offcutz** [comment]
Hi @davidarellano 
Editing just a header won't help as it's just a small portion of a whole certificate.
Those "separate files" always been in that location as they're simply private keys downloaded from the authorization server. 
Names of those files corresponds to plugins they "unlock", for example:
AKSS1 - Studio Strings
AKSP1 - Stage Piano
AKOX1 - OPX
ARFL2 - Flavor Pro
ARDL2 - Delay Pro and so on and so on...
Public key is still embedeed in the main binary and in version 2.12.1.41 it's starts at offset 1983F92.
Unfortunately without knowing the proper algorithm (RSA ?) there are slim chances to unlock it without further hassle
Last time I've check it with ghidra, it was doing some funky operations on that key and unfortunately I don't have enough knowledge / skills to fully follow along without wasting time lol.

**Comment by morpheasgr** [comment]
😢 never got the OG patched MPC binary to run on the device (mind that I have a Force, not an MPC), cuz I was using an overlay and mostly cuz I compiled and ran the patcher on x86_64 windows.

A friend compiled the patcher for me on a device of proper architecture but I we were now on a new firmware with a new activation Algo/encryption.

Sadly too few people own this kind of hardware and the only RE "God" I know is busy and doesn't have time or motive to look into this.

Heck, simulating the correct environment to develop for the platform on PC required WSL, QEMU and a bunch of prep work, even with script automation we came up with.

I'm giving up home now, too bad I actually wasted trials for this.

Haven't been able to fully utilize this expensive piece of gear because my productions require virtual instruments that might not exist or sound proper. Stuff like scarbee Rickenbacker bass, Rhodes/pianos, and of course synths such as serum, diva etc.

And the saddest thing is, I thought Ableton Push functionality would have been ported over to the Force 1:1 and gave away the Push 2 while they nerfed the pad matrix into a clip launcher/launchpad...
No drum rack control, no step sequencing, no scale setting. Can't always carry keyboards around, or Ethernet adapters.... Not having midi/das Mode via supplied USB is dumb af.

I have found decompiled python scripts for Ableton 11 here on github (control surface Scripts) for both the Push series and the Force, but while I know python I have no clue how to create a chimera, bringing back the nerfed features. The usual suspects have not made any script mods or maxmssp stuff for the Force yet.

The firmware for the Force has been rooted by mockba, we can run custom code, we can multiboot old versions and basically tons of CLI and stuff, we can extend the functionalities.

But nobody interested in the feature I am looking for, which is to basically have back the Push controller mode features I was expecting. Just too fast on a PC DAW to switch over to doing composition fully onboard, especially when the darn plugins cost so much and I can't find what I need. 

Have bought at least two plugins already but they're pricey and I have no clue whether they're worth the investment.

Also wish I could work with my own sample folders much easier/seamlessly.
